[package]
name = "calc-core"
version = "0.1.0"
edition = "2021"
# calc-core.workspace = true

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
